server:
  port: 8005
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vstudb?currentSchema=abiturient
    username: vstu_abiturient
    password: vstu_abiturient
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      uri: http://localhost:8000
  application:
    name: admission-committee-service
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  mail:
    username: vstu.mailer@gmail.com
    password: vstu.mailer@gmail.com
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true
          ssl.trust: smtp.gmail.com
        debug: false
        smtps.debug: false
mailer:
  dev.exception: g1ash1501@gmail.com
token:
  signing.key: bgM8ZUALPlm4nij35kFx1dp1yRzL4aAvsvWwrGlykx9T05Lgt7J53kaJ6BzbozNsGIQJR71n5NGzljd4Ae3wWhdSUnAkFIdIXCQmnkMlRvx1RwxMj3pQeArUg2K5eAhcNSPjTxthVslTemwO2GMRnm01HQPOa9R8m5fWuFdma3G1ZElZ0n8ctQ4n7KeZTLAhzMg5qSpNr2MrgkTYfrE9ci2VreGKMBo5O4TFyK52kY5m6HvlOCmcfZ5D8346KlJ
eureka:
  client:
    enabled: false